#!/usr/bin/env python

import argparse, os, pprint, sys

parser = argparse.ArgumentParser()
parser.add_argument('sysroot')
parser.add_argument('input')
parser.add_argument('output')

args = parser.parse_args()

values = {}

with open(args.input, 'r') as fobj:
    exec(fobj.read(), globals(), values)
    values = values['build_time_vars']

    for key in [ 'CONFINCLUDEPY', 'INCLUDEPY', 'LIBDIR' ]:
        #print('updating %s' % key)
        if key in values:
            values[key] = args.sysroot + values[key]
            #print('  %s: %s' % (key, values[key]))
        #else:
            #print('  not found')

with open(args.output, 'w') as fobj:
    fobj.write('build_time_vars = ')
    pprint.pprint(values, fobj)
