#!/usr/bin/python

import os, os.path
import readline
import sys

srctree = os.path.realpath(os.path.dirname(sys.argv[0]))
scripts_dir = os.path.join(srctree, 'scripts')
sys.path.insert(1, scripts_dir)

import pbs.commands, pbs.db, pbs.project

commands = pbs.commands.load(pbs.srctree)
db = pbs.db.Database()
db.load(pbs.srctree)
db.dump(0)

project = pbs.project.Project(db)
project.load()

print('source directory:', pbs.srctree)
print('output directory:', pbs.objtree)

while True:
    try:
        command = input('> ')
    except EOFError:
        print()
        break

    if not command:
        continue

    args = command.split()

    if args[0] not in commands:
        print('unknown command "%s"' % args[0])
        continue

    try:
        commands[args[0]].exec(project, *args)
    except EOFError:
        break

project.save()

# vim: et sts=4 sw=4 ts=4
