#!/usr/bin/python3

import click, os.path, sys

srctree = os.path.realpath(os.path.dirname(sys.argv[0]))
scripts_dir = os.path.join(srctree, 'scripts')
sys.path.insert(1, scripts_dir)

import pbs.cli

if __name__ == '__main__':
    context = pbs.cli.ContextObject()
    pbs.cli.CLI(obj = context)()
    context.project.save()

# vim: et sts=4 sw=4 ts=4
