ARCH = $(arch)
ARCH_LONG = $(arch.generation)
ENDIAN = little

VENDOR = unknown
OS = linux
LIBC = gnu

HOST = $(ARCH_LONG)-$(VENDOR)-$(OS)-$(LIBC)
CFLAGS = -march=$(arch.generation) -mcpu=$(arch.cpu)
